version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: carttracker
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Exposing PostgreSQL on port 5433 externally

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"  # Exposing Redis on port 6380 externally

  web:
    build: .
    command: gunicorn --workers 2 --worker-connections 1000 --timeout 300 --bind 0.0.0.0:8000 aicarttracker.wsgi:application  # Adjust workers and timeout as needed
    volumes:
      - .:/app
      - ./product_data.csv:/app/product_data.csv
    ports:
      - "8000:8000"  # Exposing web app on port 8000
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=carttracker
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6380/0
    shm_size: '4gb'  # Increased shared memory size to handle heavy operations (important for Selenium)

  test:
    build: .
    command: python manage.py test  # Runs the tests
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=carttracker
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
