apiVersion: apps/v1
kind: Deployment
metadata:
  name: aicarttracker-deployment
  labels:
    app: aicarttracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aicarttracker
  template:
    metadata:
      labels:
        app: aicarttracker
    spec:
      containers:
        - name: web
          image: ashikarjen/aicarttracker:v1
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: aicarttracker-config
                  key: database_name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: aicarttracker-secrets
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aicarttracker-secrets
                  key: database_password
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
