# Generated by Django 5.1.1 on 2024-09-27 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('daraz_id', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('sentiment', models.CharField(max_length=10)),
                ('date_posted', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tracker.product')),
            ],
        ),
    ]
